spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/research_gap_finder}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  thymeleaf:
    cache: false

server:
  port: ${PORT:8080}
